### ISSUE TITLE
Adding multiple disable queries only uses the first one

### ISSUE THREAD

**Issue by drewwells** [futuweb/webpack-amdi18n-loader#10]
With a disable query as such: `?disable=[__noOverlay,__defaultNoOverlayLocale]` only the first __noOverlay is added to the disable list.

**Comment by TooBug** [comment]
I'll check it.

**Comment by TooBug** [comment]
Fixed in 0.5.2.

Notice: the separator changed to `|`, because the comma seems not usable in query content.

**Comment by drewwells** [comment]
you're a rockstar! 💯
