### ISSUE TITLE
support loader config

### ISSUE THREAD

**Issue by drewwells** [futuweb/webpack-amdi18n-loader#11]
What is observed:
```
require('ojL10n?enable=[en-us]&disable=[__defaultNoOverlayLocale]!ojtranslations/nls/localeElements')
// enable filter [en-us]
// disable filter [__defaultNoOverlayLocale]
require('ojL10n!ojtranslations/nls/localeElements')
// enable filter []
// disable filter []
```

What is expected
```
require('ojL10n?enable=[en-us]&disable=[__defaultNoOverlayLocale]!ojtranslations/nls/localeElements')
// enable filter [en-us]
// disable filter [__defaultNoOverlayLocale]
require('ojL10n!ojtranslations/nls/localeElements')
// enable filter [en-us]
// disable filter [__defaultNoOverlayLocale]
```

I believe that README mentions that disabling a locale permanently removes it. So I would expect the second require() call to disable __defaultNoOverlayLocale.

**Comment by drewwells** [comment]
A global way to configure the locales to load would be nice. A quick and dirty solution might be to throw a warning rather than an error on missing locales here: https://github.com/futuweb/webpack-amdi18n-loader/blob/master/index.js#L26

**Comment by TooBug** [comment]
As far as I know, there is no way to provider a global configure to a loader. Maybe you can add it to the `webpack.config.js` to globally deal with this situation.

**Comment by drewwells** [comment]
It looks like this is the webpack 2 way of configuring a loader. Maybe this provides some insight? https://webpack.js.org/concepts/loaders/#configuration

**Comment by TooBug** [comment]
It's the same as webpack 1. You can specify the configure in `require(amdi18n?abc!xxx)`, you can also specify in `webpack.config.js`. If you use the later, you can write like this `require(xxx)` in your code.

**Comment by TooBug** [comment]
BTW, Only root file and used lang files would be read, So I think if they are not exist, an error is the proper way.

**Comment by drewwells** [comment]
This looks like the required change to allow global configuration of white|black list. It could use some validation to ensure an array is passed via config. Also, some consideration if query string is additive to the global config or overrides it.

```
+       var config = loaderUtils.getLoaderConfig(this, "amdi18n")
        var query = loaderUtils.parseQuery(this.query);

        // whitelist / blacklist
-       var enableList = [];
-       var disableList = [];
+       var enableList = config.enableList || [];
+       var disableList = config.disableList || [];
```

**Comment by TooBug** [comment]
Good! I’ll see it later.
