### ISSUE TITLE
请教一下require.config.i18n 怎么传递到你的loader里面呢？ 

### ISSUE THREAD

**Issue by YiyangLi** [futuweb/webpack-amdi18n-loader#12]
首先，非常感谢你写了这么棒的一个lib，直接就可以用了。可是我自己的project有一些复杂， 就是我在 require.config.js 里面定义了config，这样把我的locale传递给i18n, 请问你这个是怎么实现的呢？ 

大概就是这样
```
requirejs.config({
    config: {
        //Set the config for the i18n
        //module ID
        i18n: {
            locale: 'fr-fr'
        }
    }
});
```

谢谢你的回答！

**Comment by TooBug** [comment]
目前不支持这样的使用方式。这主要是因为require.js和webpack的原理不一致导致的。

require.js是在runtime时读取和使用配置的，可以根据外界条件动态计算指定配置文件中的`locale`并加载对应的语言文件，而webpack是在build时读取和使用配置的。如果webpack直接读取配置文件中的i18n配置的话，那就无法在runtime动态选择语言了，只能build出一种语言的文件。

所以使用webpack的话，要全局指定语言，可以选择使用全局变量或者`html[lang]`属性来指定需要使用的语言。

**Comment by YiyangLi** [comment]
谢谢你。现在我还碰到了最大长度的限制，我开了另外一个issue，相信你也看到了。

在这里，我能请教你另一个很简单（其实也略复杂）的问题吗？ 

假设 我有一个Framework module，且称呼为fmk。然后我有我自己的project，称为index。

那fmk里面有很多控件，比如list，list下面可能有小控件，比如row。这个fmk的main文件暴露了常用且基础控件，如这个list，但是复杂的，如list下面的row就没暴露出来。
这样我使用list的时候就可以这样

```
define(['fmk'], function(fmk) {
   return fmk.list.extend();
});
```

在index 项目里面呢，偶尔也有一些页面需要定制一下row，于是可以引用row，引用如下 
```
define(['fmk/list/row'], function (row) {
   return row.extend();
});
```

那我现在用了webpack，我把fmk源文件拷贝后打包index项目没毛病，运行也很好。现在我要先打包fmk，然后拷贝打包后的fmk 和其他所有源文件给index，打包没有问题，通过的。但是使用的时候，就会在引用`'fmk/list/row'` 后说row 没有定义。

这个简化的模型就是说，夫模块下有打包好的子模块，内含常用的孙子模块，但夫模块仍然引用了没有直接暴露在子模块下的其他孙子模块，这样打包没问题，使用的时候出现了undefined。

你知道这样的问题能解决吗？

**Comment by TooBug** [comment]
这问题跟本插件无关，后续建议不要在这里提无关问题。


本质上是一个寻址的问题，你可以学习一下Node的require方法。`a/b/c`并不是指a模块中的b成员中的c成员，而是指目录a/b下的c.js。如果文件不存在，自然无法引用。顺着这个思路自己可以找到解决办法，要么把文件保留，要么将它暴露到模块成员中使用。

**Comment by yiyangli-okta** [comment]
好的，你介意提供你的邮箱吗？我觉得我是懂node 的寻址的，但是后半句不是很理解，不理解如何把文件保留。

无论如何，谢谢你啦。

**Comment by TooBug** [comment]
微博@TooBug
