### ISSUE TITLE
Support root as a locale bundle

### ISSUE THREAD

**Issue by Georgegriff** [futuweb/webpack-amdi18n-loader#14]
My legacy code base (migrating from RequireJS) has its "root" bundle, as per the examples on Requirejs (http://requirejs.org/docs/api.html#i18n)  for i18n files configured as such:
//my/nls/colors.js contents:

define({
    "root": true,
    "fr-fr": true,
    "fr-fr-paris": true
});
//Contents of my/nls/root/colors.js

define({
    "red": "red",
    "blue": "blue",
    "green": "green"
});

When using amdi18n it does not appear to pick up the values from my "colors.js" under /root/, is it possible to use the loader in this way? I am unable to modify our resource files because i cannot touch the code base as we have legacy integrations to support.

Cheers

**Comment by TooBug** [comment]
Thanks for your reporting. I’ve investigated at i18n plugin docs for require.js, and confirmed amdi18n-loader missed the usage at the very bottom:

> If you prefer to not include the root bundle in the top level module, you can define it like a normal locale bundle. 

I’ll update get amdi18n-loader supporting this kind of usage ASAP.

**Comment by TooBug** [comment]
available in 0.6.0

**Comment by Georgegriff** [comment]
Excellent :) thanks
