### ISSUE TITLE
support webpack 4

### ISSUE THREAD

**Issue by komali2** [futuweb/webpack-amdi18n-loader#22]
amdi18n-loader is triggering `Module build failed: Error: A valid query string passed to parseQuery should begin with '?'`

Likely it is because of the same issue seen here: https://github.com/jballant/webpack-strip-block/issues/4

See in `index.js`

```
module.exports = function (content) {
	var query = loaderUtils.parseQuery(this.query);


```

Change to 

`var query = (this.query === '' ? {} : loaderUtils.parseQuery(this.query));`

To prevent this from ever happening.

**Comment by komali2** [comment]
See also https://github.com/babel/babel-loader/issues/392

**Comment by komali2** [comment]
Also, I'm not sure how, but looking directly at the node_modules folder, this has an out-of-date version of loader-utils being installed. I'm not sure how this is possible considering it's not in the package.json.

**Comment by komali2** [comment]
oh, this whole thing is because of the fact that a version of webpack less than 2 is being required.

**Comment by TooBug** [comment]
Got. Can you please tell the environment? For example, which version of webpack you are using , etc.

I'll inspect this problem, and fix it if needed.

**Comment by komali2** [comment]
I see you - we're in different time zones, it's nearly 11 here, if it's alright with you I'll post my findings tomorrow.

**Comment by TooBug** [comment]
Please just post. No worry about time zones. I'll inspect once I receive the notice from Github.

**Comment by komali2** [comment]
Ok, so the issue happened when we were using Webpack v3.11.0, and disappeared when we upgraded to Webpack 4. Super weird. 

I noticed in the node_modules of amdi18n-loader, Webpack 2 was present. It's hard for me to reproduce on our repo now because we're on webpack 4, let me see if I can get it working in a dummy repo.

**Comment by TooBug** [comment]
OK, If any problem, please post here.

I'll keep this issue open until I  can confirm this problem not occur in webpack 1/2/3/4. Do this check later.
