### ISSUE TITLE
Support ES6 import statement

### ISSUE THREAD

**Issue by pankajvishwani** [futuweb/webpack-amdi18n-loader#24]
I just upgraded to 0.8.0, where ```export default {}``` is now supported. But I have a use case where I want to be able to import root object from another file. Something like the following:

component_root.js:
```
export default {
	label: "Select Label",
	nofound: "Notfound",
	loading: "Loading...",
	errloading: "Error loading data"
};
```
component_i18n.js:
```
import root from "./component_root";

export default {
	root,
	ja: true,
	zh: true,
	ko: true
};
```

Can this be supported? I am trying to integrate unit test cases, where I need to pass root object directly. Otherwise I will have to maintain two separate files, one for running unit tests and another for actual rendering.

**Comment by TooBug** [comment]
Sorry, It's not supported right now.

Maybe you should use CommonJS or json for `component_root.js`, and import via CommonJS `require`.

**Comment by TooBug** [comment]
I'm not so sure, Maybe import via CommonJS is not supported as well.

But, what you want may be done by this <https://github.com/futuweb/webpack-amdi18n-loader/tree/master/tests/root-true>

**Comment by pankajvishwani** [comment]
Cool. This works too. Thanks!!
