### ISSUE TITLE
functionality of enable/disable

### ISSUE THREAD

**Issue by drewwells** [futuweb/webpack-amdi18n-loader#9]
The docs mention enable, but the default of this plugin enables all languages. So how does this behave differently?

If I have 60 languages available and only want to build 1. Do I enable that one language or disable the other 59?

**Comment by TooBug** [comment]
Yes, the default behavior is using all the languages. But either `enable` or `disable` will break it.


So you can just use `enable=xx` to use `xx` language, all other languages will not be touched.

**Comment by drewwells** [comment]
Sweet it works! Thanks so much. If I common build some paths. Do the paths
in my app also need the query string to use these settings? Some code is
third party so I can't modify them, but I can resolve alias them if they
will preserve the query string...

**Comment by TooBug** [comment]
Not quite understood.

Do you mean, you want to modify some `require('amdi18n!xxx')` from the outside world?

I'm not very sure about this. In webpack 2, it seems to be a more detailed match rule on loaders, you can look up the docs, maybe.
